// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type IndexerPool struct {
	PoolAddress string
	Creator     string
}

type LivestreamStream struct {
	ID               string
	PoolAddress      string
	CreatorWallet    string
	Title            string
	LivepeerStreamID string
	StreamKey        string
	PlaybackID       string
	RtmpUrl          string
	PlaybackUrl      string
	IsLive           bool
	ViewerCount      int64
	StartedAt        *int64
	EndedAt          *int64
	CreatedAt        int64
}
