// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcdb

import (
	"context"
)

const countActiveStreamsByWallet = `-- name: CountActiveStreamsByWallet :one
SELECT count(*) FROM livestream.streams
WHERE creator_wallet = $1 AND is_live = true
`

func (q *Queries) CountActiveStreamsByWallet(ctx context.Context, creatorWallet string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStreamsByWallet, creatorWallet)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStream = `-- name: CreateStream :exec
INSERT INTO livestream.streams (
	id, pool_address, creator_wallet, title,
	livepeer_stream_id, stream_key, playback_id, rtmp_url, playback_url,
	is_live, viewer_count, started_at, ended_at, created_at
) VALUES (
	$1, $2, $3, $4,
	$5, $6, $7, $8, $9,
	false, 0, NULL, NULL, $10
)
`

type CreateStreamParams struct {
	ID               string
	PoolAddress      string
	CreatorWallet    string
	Title            string
	LivepeerStreamID string
	StreamKey        string
	PlaybackID       string
	RtmpUrl          string
	PlaybackUrl      string
	CreatedAt        int64
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) error {
	_, err := q.db.Exec(ctx, createStream,
		arg.ID,
		arg.PoolAddress,
		arg.CreatorWallet,
		arg.Title,
		arg.LivepeerStreamID,
		arg.StreamKey,
		arg.PlaybackID,
		arg.RtmpUrl,
		arg.PlaybackUrl,
		arg.CreatedAt,
	)
	return err
}

const endStream = `-- name: EndStream :exec
UPDATE livestream.streams SET is_live = false, ended_at = $2 WHERE id = $1
`

type EndStreamParams struct {
	ID      string
	EndedAt *int64
}

func (q *Queries) EndStream(ctx context.Context, arg EndStreamParams) error {
	_, err := q.db.Exec(ctx, endStream, arg.ID, arg.EndedAt)
	return err
}

const getPoolCreator = `-- name: GetPoolCreator :one

SELECT creator FROM indexer.pools WHERE pool_address = $1 LIMIT 1
`

// query.sql — sqlc query definitions for media/livestream (streams CRUD + the
// cross-schema creator lookup). Ported 1:1 from routes/streams.ts drizzle calls.
// Cross-schema read (indexer.pools) used to verify the caller owns the pool.
func (q *Queries) GetPoolCreator(ctx context.Context, poolAddress string) (string, error) {
	row := q.db.QueryRow(ctx, getPoolCreator, poolAddress)
	var creator string
	err := row.Scan(&creator)
	return creator, err
}

const getStreamByID = `-- name: GetStreamByID :one
SELECT id, pool_address, creator_wallet, title, livepeer_stream_id, stream_key, playback_id, rtmp_url, playback_url, is_live, viewer_count, started_at, ended_at, created_at FROM livestream.streams WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStreamByID(ctx context.Context, id string) (LivestreamStream, error) {
	row := q.db.QueryRow(ctx, getStreamByID, id)
	var i LivestreamStream
	err := row.Scan(
		&i.ID,
		&i.PoolAddress,
		&i.CreatorWallet,
		&i.Title,
		&i.LivepeerStreamID,
		&i.StreamKey,
		&i.PlaybackID,
		&i.RtmpUrl,
		&i.PlaybackUrl,
		&i.IsLive,
		&i.ViewerCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStreamLiveStatus = `-- name: GetStreamLiveStatus :one
SELECT id, is_live FROM livestream.streams WHERE id = $1 LIMIT 1
`

type GetStreamLiveStatusRow struct {
	ID     string
	IsLive bool
}

func (q *Queries) GetStreamLiveStatus(ctx context.Context, id string) (GetStreamLiveStatusRow, error) {
	row := q.db.QueryRow(ctx, getStreamLiveStatus, id)
	var i GetStreamLiveStatusRow
	err := row.Scan(&i.ID, &i.IsLive)
	return i, err
}

const listLiveStreams = `-- name: ListLiveStreams :many
SELECT id, pool_address, creator_wallet, title, playback_url, playback_id,
       is_live, viewer_count, started_at, created_at
FROM livestream.streams
WHERE is_live = true
ORDER BY started_at DESC
LIMIT 50
`

type ListLiveStreamsRow struct {
	ID            string
	PoolAddress   string
	CreatorWallet string
	Title         string
	PlaybackUrl   string
	PlaybackID    string
	IsLive        bool
	ViewerCount   int64
	StartedAt     *int64
	CreatedAt     int64
}

func (q *Queries) ListLiveStreams(ctx context.Context) ([]ListLiveStreamsRow, error) {
	rows, err := q.db.Query(ctx, listLiveStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveStreamsRow{}
	for rows.Next() {
		var i ListLiveStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolAddress,
			&i.CreatorWallet,
			&i.Title,
			&i.PlaybackUrl,
			&i.PlaybackID,
			&i.IsLive,
			&i.ViewerCount,
			&i.StartedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolStreams = `-- name: ListPoolStreams :many
SELECT id, pool_address, creator_wallet, title, playback_url, playback_id,
       is_live, viewer_count, started_at, ended_at, created_at
FROM livestream.streams
WHERE pool_address = $1
  AND (NOT $2::boolean OR is_live = true)
ORDER BY created_at DESC
LIMIT 20
`

type ListPoolStreamsParams struct {
	PoolAddress string
	LiveOnly    bool
}

type ListPoolStreamsRow struct {
	ID            string
	PoolAddress   string
	CreatorWallet string
	Title         string
	PlaybackUrl   string
	PlaybackID    string
	IsLive        bool
	ViewerCount   int64
	StartedAt     *int64
	EndedAt       *int64
	CreatedAt     int64
}

// When live_only is true, only currently-live streams are returned; otherwise
// all streams for the pool. (Collapses the TS conditional drizzle query.)
func (q *Queries) ListPoolStreams(ctx context.Context, arg ListPoolStreamsParams) ([]ListPoolStreamsRow, error) {
	rows, err := q.db.Query(ctx, listPoolStreams, arg.PoolAddress, arg.LiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoolStreamsRow{}
	for rows.Next() {
		var i ListPoolStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolAddress,
			&i.CreatorWallet,
			&i.Title,
			&i.PlaybackUrl,
			&i.PlaybackID,
			&i.IsLive,
			&i.ViewerCount,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStreamIdleByLivepeerID = `-- name: SetStreamIdleByLivepeerID :exec
UPDATE livestream.streams SET is_live = false, ended_at = $2 WHERE livepeer_stream_id = $1
`

type SetStreamIdleByLivepeerIDParams struct {
	LivepeerStreamID string
	EndedAt          *int64
}

func (q *Queries) SetStreamIdleByLivepeerID(ctx context.Context, arg SetStreamIdleByLivepeerIDParams) error {
	_, err := q.db.Exec(ctx, setStreamIdleByLivepeerID, arg.LivepeerStreamID, arg.EndedAt)
	return err
}

const setStreamLive = `-- name: SetStreamLive :exec
UPDATE livestream.streams SET is_live = true, started_at = $2 WHERE id = $1
`

type SetStreamLiveParams struct {
	ID        string
	StartedAt *int64
}

func (q *Queries) SetStreamLive(ctx context.Context, arg SetStreamLiveParams) error {
	_, err := q.db.Exec(ctx, setStreamLive, arg.ID, arg.StartedAt)
	return err
}

const setStreamLiveByLivepeerID = `-- name: SetStreamLiveByLivepeerID :exec
UPDATE livestream.streams SET is_live = true, started_at = $2 WHERE livepeer_stream_id = $1
`

type SetStreamLiveByLivepeerIDParams struct {
	LivepeerStreamID string
	StartedAt        *int64
}

func (q *Queries) SetStreamLiveByLivepeerID(ctx context.Context, arg SetStreamLiveByLivepeerIDParams) error {
	_, err := q.db.Exec(ctx, setStreamLiveByLivepeerID, arg.LivepeerStreamID, arg.StartedAt)
	return err
}

const updateViewerCount = `-- name: UpdateViewerCount :exec
UPDATE livestream.streams SET viewer_count = $2 WHERE id = $1
`

type UpdateViewerCountParams struct {
	ID          string
	ViewerCount int64
}

func (q *Queries) UpdateViewerCount(ctx context.Context, arg UpdateViewerCountParams) error {
	_, err := q.db.Exec(ctx, updateViewerCount, arg.ID, arg.ViewerCount)
	return err
}
