// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	CountActiveStreamsByWallet(ctx context.Context, creatorWallet string) (int64, error)
	CreateStream(ctx context.Context, arg CreateStreamParams) error
	EndStream(ctx context.Context, arg EndStreamParams) error
	// query.sql — sqlc query definitions for media/livestream (streams CRUD + the
	// cross-schema creator lookup). Ported 1:1 from routes/streams.ts drizzle calls.
	// Cross-schema read (indexer.pools) used to verify the caller owns the pool.
	GetPoolCreator(ctx context.Context, poolAddress string) (string, error)
	GetStreamByID(ctx context.Context, id string) (LivestreamStream, error)
	GetStreamLiveStatus(ctx context.Context, id string) (GetStreamLiveStatusRow, error)
	ListLiveStreams(ctx context.Context) ([]ListLiveStreamsRow, error)
	// When live_only is true, only currently-live streams are returned; otherwise
	// all streams for the pool. (Collapses the TS conditional drizzle query.)
	ListPoolStreams(ctx context.Context, arg ListPoolStreamsParams) ([]ListPoolStreamsRow, error)
	SetStreamIdleByLivepeerID(ctx context.Context, arg SetStreamIdleByLivepeerIDParams) error
	SetStreamLive(ctx context.Context, arg SetStreamLiveParams) error
	SetStreamLiveByLivepeerID(ctx context.Context, arg SetStreamLiveByLivepeerIDParams) error
	UpdateViewerCount(ctx context.Context, arg UpdateViewerCountParams) error
}

var _ Querier = (*Queries)(nil)
