// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IndexerPool struct {
	PoolAddress  string
	TokenAddress string
	Creator      string
	CreatedAt    int64
}

type UsersUserImage struct {
	ID            string
	WalletAddress string
	ImageType     string
	StorageKey    string
	MimeType      string
	SizeBytes     int32
	UploadedAt    int64
}

type UsersUserProfile struct {
	WalletAddress string
	DisplayName   pgtype.Text
	Bio           pgtype.Text
	Twitter       pgtype.Text
	Telegram      pgtype.Text
	Discord       pgtype.Text
	Website       pgtype.Text
	CreatedAt     int64
	UpdatedAt     int64
}

type UsersWatchlist struct {
	WalletAddress string
	PoolAddress   string
	AddedAt       int64
}
