// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	AddWatchlist(ctx context.Context, arg AddWatchlistParams) error
	GetImageByType(ctx context.Context, arg GetImageByTypeParams) (UsersUserImage, error)
	GetUserImages(ctx context.Context, walletAddress string) ([]UsersUserImage, error)
	// query.sql — sqlc query definitions for media/user. Ported from the TS
	// index.ts drizzle calls. All wallet/creator matches are case-insensitive
	// (LOWER(...)); writes are lowercased by the handler so reads stay stable.
	GetUserProfile(ctx context.Context, walletAddress string) (UsersUserProfile, error)
	GetWatchlist(ctx context.Context, walletAddress string) ([]GetWatchlistRow, error)
	// Cross-schema read (indexer.pools) — pools created by this wallet.
	ListCreatedPools(ctx context.Context, creator string) ([]ListCreatedPoolsRow, error)
	RemoveWatchlist(ctx context.Context, arg RemoveWatchlistParams) error
	UpsertUserImage(ctx context.Context, arg UpsertUserImageParams) error
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
