// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWatchlist = `-- name: AddWatchlist :exec
INSERT INTO users.watchlists (wallet_address, pool_address, added_at)
VALUES ($1, $2, $3)
ON CONFLICT (wallet_address, pool_address) DO NOTHING
`

type AddWatchlistParams struct {
	WalletAddress string
	PoolAddress   string
	AddedAt       int64
}

func (q *Queries) AddWatchlist(ctx context.Context, arg AddWatchlistParams) error {
	_, err := q.db.Exec(ctx, addWatchlist, arg.WalletAddress, arg.PoolAddress, arg.AddedAt)
	return err
}

const getImageByType = `-- name: GetImageByType :one
SELECT id, wallet_address, image_type, storage_key, mime_type, size_bytes, uploaded_at FROM users.user_images
WHERE LOWER(wallet_address) = $1 AND image_type = $2
LIMIT 1
`

type GetImageByTypeParams struct {
	WalletAddress string
	ImageType     string
}

func (q *Queries) GetImageByType(ctx context.Context, arg GetImageByTypeParams) (UsersUserImage, error) {
	row := q.db.QueryRow(ctx, getImageByType, arg.WalletAddress, arg.ImageType)
	var i UsersUserImage
	err := row.Scan(
		&i.ID,
		&i.WalletAddress,
		&i.ImageType,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const getUserImages = `-- name: GetUserImages :many
SELECT id, wallet_address, image_type, storage_key, mime_type, size_bytes, uploaded_at FROM users.user_images
WHERE LOWER(wallet_address) = $1
`

func (q *Queries) GetUserImages(ctx context.Context, walletAddress string) ([]UsersUserImage, error) {
	rows, err := q.db.Query(ctx, getUserImages, walletAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersUserImage{}
	for rows.Next() {
		var i UsersUserImage
		if err := rows.Scan(
			&i.ID,
			&i.WalletAddress,
			&i.ImageType,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfile = `-- name: GetUserProfile :one

SELECT wallet_address, display_name, bio, twitter, telegram, discord, website, created_at, updated_at FROM users.user_profiles
WHERE LOWER(wallet_address) = $1
LIMIT 1
`

// query.sql — sqlc query definitions for media/user. Ported from the TS
// index.ts drizzle calls. All wallet/creator matches are case-insensitive
// (LOWER(...)); writes are lowercased by the handler so reads stay stable.
func (q *Queries) GetUserProfile(ctx context.Context, walletAddress string) (UsersUserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, walletAddress)
	var i UsersUserProfile
	err := row.Scan(
		&i.WalletAddress,
		&i.DisplayName,
		&i.Bio,
		&i.Twitter,
		&i.Telegram,
		&i.Discord,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchlist = `-- name: GetWatchlist :many
SELECT pool_address, added_at FROM users.watchlists
WHERE LOWER(wallet_address) = $1
ORDER BY added_at DESC
`

type GetWatchlistRow struct {
	PoolAddress string
	AddedAt     int64
}

func (q *Queries) GetWatchlist(ctx context.Context, walletAddress string) ([]GetWatchlistRow, error) {
	rows, err := q.db.Query(ctx, getWatchlist, walletAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWatchlistRow{}
	for rows.Next() {
		var i GetWatchlistRow
		if err := rows.Scan(&i.PoolAddress, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatedPools = `-- name: ListCreatedPools :many
SELECT pool_address, token_address, created_at FROM indexer.pools
WHERE LOWER(creator) = $1
ORDER BY created_at DESC
`

type ListCreatedPoolsRow struct {
	PoolAddress  string
	TokenAddress string
	CreatedAt    int64
}

// Cross-schema read (indexer.pools) — pools created by this wallet.
func (q *Queries) ListCreatedPools(ctx context.Context, creator string) ([]ListCreatedPoolsRow, error) {
	rows, err := q.db.Query(ctx, listCreatedPools, creator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreatedPoolsRow{}
	for rows.Next() {
		var i ListCreatedPoolsRow
		if err := rows.Scan(&i.PoolAddress, &i.TokenAddress, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWatchlist = `-- name: RemoveWatchlist :exec
DELETE FROM users.watchlists
WHERE LOWER(wallet_address) = $1 AND LOWER(pool_address) = $2
`

type RemoveWatchlistParams struct {
	WalletAddress string
	PoolAddress   string
}

func (q *Queries) RemoveWatchlist(ctx context.Context, arg RemoveWatchlistParams) error {
	_, err := q.db.Exec(ctx, removeWatchlist, arg.WalletAddress, arg.PoolAddress)
	return err
}

const upsertUserImage = `-- name: UpsertUserImage :exec
INSERT INTO users.user_images (
	id, wallet_address, image_type, storage_key, mime_type, size_bytes, uploaded_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
	storage_key = EXCLUDED.storage_key,
	mime_type   = EXCLUDED.mime_type,
	size_bytes  = EXCLUDED.size_bytes,
	uploaded_at = EXCLUDED.uploaded_at
`

type UpsertUserImageParams struct {
	ID            string
	WalletAddress string
	ImageType     string
	StorageKey    string
	MimeType      string
	SizeBytes     int32
	UploadedAt    int64
}

func (q *Queries) UpsertUserImage(ctx context.Context, arg UpsertUserImageParams) error {
	_, err := q.db.Exec(ctx, upsertUserImage,
		arg.ID,
		arg.WalletAddress,
		arg.ImageType,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedAt,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec
INSERT INTO users.user_profiles (
	wallet_address, display_name, bio, twitter, telegram, discord, website,
	created_at, updated_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (wallet_address) DO UPDATE SET
	display_name = EXCLUDED.display_name,
	bio          = EXCLUDED.bio,
	twitter      = EXCLUDED.twitter,
	telegram     = EXCLUDED.telegram,
	discord      = EXCLUDED.discord,
	website      = EXCLUDED.website,
	updated_at   = EXCLUDED.updated_at
`

type UpsertUserProfileParams struct {
	WalletAddress string
	DisplayName   pgtype.Text
	Bio           pgtype.Text
	Twitter       pgtype.Text
	Telegram      pgtype.Text
	Discord       pgtype.Text
	Website       pgtype.Text
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfile,
		arg.WalletAddress,
		arg.DisplayName,
		arg.Bio,
		arg.Twitter,
		arg.Telegram,
		arg.Discord,
		arg.Website,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
