// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IndexerPool struct {
	PoolAddress  string
	TokenAddress string
	Creator      string
}

type MetadataTokenImage struct {
	ID           string
	TokenAddress string
	ImageType    string
	StorageKey   string
	MimeType     string
	SizeBytes    int32
	UploadedAt   int64
}

type MetadataTokenMetadatum struct {
	TokenAddress string
	PoolAddress  string
	Name         pgtype.Text
	Symbol       pgtype.Text
	Description  pgtype.Text
	Website      pgtype.Text
	Twitter      pgtype.Text
	Telegram     pgtype.Text
	Discord      pgtype.Text
	CustomTags   pgtype.Text
	CreatedBy    string
	CreatedAt    int64
	UpdatedAt    int64
	Decimals     int32
}
