// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	GetImageByType(ctx context.Context, arg GetImageByTypeParams) (MetadataTokenImage, error)
	// query.sql — sqlc query definitions for media/metadata. Ported from the TS
	// index.ts drizzle calls. All token-address matches are case-insensitive
	// (LOWER(...)); writes are lowercased by the handler so reads stay stable.
	// Cross-schema read (indexer.pools) — verifies the token exists + creator gate.
	GetPoolByToken(ctx context.Context, tokenAddress string) (IndexerPool, error)
	GetTokenImages(ctx context.Context, tokenAddress string) ([]MetadataTokenImage, error)
	GetTokenMetadata(ctx context.Context, tokenAddress string) (MetadataTokenMetadatum, error)
	ListPoolsByTokenAddrs(ctx context.Context, addrs []string) ([]IndexerPool, error)
	ListTokenImagesByAddrs(ctx context.Context, addrs []string) ([]MetadataTokenImage, error)
	ListTokenMetadataByAddrs(ctx context.Context, addrs []string) ([]MetadataTokenMetadatum, error)
	UpsertTokenImage(ctx context.Context, arg UpsertTokenImageParams) error
	UpsertTokenMetadata(ctx context.Context, arg UpsertTokenMetadataParams) error
}

var _ Querier = (*Queries)(nil)
