// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getImageByType = `-- name: GetImageByType :one
SELECT id, token_address, image_type, storage_key, mime_type, size_bytes, uploaded_at FROM metadata.token_images
WHERE LOWER(token_address) = $1 AND image_type = $2
LIMIT 1
`

type GetImageByTypeParams struct {
	TokenAddress string
	ImageType    string
}

func (q *Queries) GetImageByType(ctx context.Context, arg GetImageByTypeParams) (MetadataTokenImage, error) {
	row := q.db.QueryRow(ctx, getImageByType, arg.TokenAddress, arg.ImageType)
	var i MetadataTokenImage
	err := row.Scan(
		&i.ID,
		&i.TokenAddress,
		&i.ImageType,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedAt,
	)
	return i, err
}

const getPoolByToken = `-- name: GetPoolByToken :one

SELECT pool_address, token_address, creator
FROM indexer.pools
WHERE LOWER(token_address) = $1
LIMIT 1
`

// query.sql — sqlc query definitions for media/metadata. Ported from the TS
// index.ts drizzle calls. All token-address matches are case-insensitive
// (LOWER(...)); writes are lowercased by the handler so reads stay stable.
// Cross-schema read (indexer.pools) — verifies the token exists + creator gate.
func (q *Queries) GetPoolByToken(ctx context.Context, tokenAddress string) (IndexerPool, error) {
	row := q.db.QueryRow(ctx, getPoolByToken, tokenAddress)
	var i IndexerPool
	err := row.Scan(&i.PoolAddress, &i.TokenAddress, &i.Creator)
	return i, err
}

const getTokenImages = `-- name: GetTokenImages :many
SELECT id, token_address, image_type, storage_key, mime_type, size_bytes, uploaded_at FROM metadata.token_images
WHERE LOWER(token_address) = $1
`

func (q *Queries) GetTokenImages(ctx context.Context, tokenAddress string) ([]MetadataTokenImage, error) {
	rows, err := q.db.Query(ctx, getTokenImages, tokenAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataTokenImage{}
	for rows.Next() {
		var i MetadataTokenImage
		if err := rows.Scan(
			&i.ID,
			&i.TokenAddress,
			&i.ImageType,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenMetadata = `-- name: GetTokenMetadata :one
SELECT token_address, pool_address, name, symbol, description, website, twitter, telegram, discord, custom_tags, created_by, created_at, updated_at, decimals FROM metadata.token_metadata
WHERE LOWER(token_address) = $1
LIMIT 1
`

func (q *Queries) GetTokenMetadata(ctx context.Context, tokenAddress string) (MetadataTokenMetadatum, error) {
	row := q.db.QueryRow(ctx, getTokenMetadata, tokenAddress)
	var i MetadataTokenMetadatum
	err := row.Scan(
		&i.TokenAddress,
		&i.PoolAddress,
		&i.Name,
		&i.Symbol,
		&i.Description,
		&i.Website,
		&i.Twitter,
		&i.Telegram,
		&i.Discord,
		&i.CustomTags,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Decimals,
	)
	return i, err
}

const listPoolsByTokenAddrs = `-- name: ListPoolsByTokenAddrs :many
SELECT pool_address, token_address, creator FROM indexer.pools
WHERE LOWER(token_address) = ANY($1::text[])
`

func (q *Queries) ListPoolsByTokenAddrs(ctx context.Context, addrs []string) ([]IndexerPool, error) {
	rows, err := q.db.Query(ctx, listPoolsByTokenAddrs, addrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IndexerPool{}
	for rows.Next() {
		var i IndexerPool
		if err := rows.Scan(&i.PoolAddress, &i.TokenAddress, &i.Creator); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenImagesByAddrs = `-- name: ListTokenImagesByAddrs :many
SELECT id, token_address, image_type, storage_key, mime_type, size_bytes, uploaded_at FROM metadata.token_images
WHERE LOWER(token_address) = ANY($1::text[])
`

func (q *Queries) ListTokenImagesByAddrs(ctx context.Context, addrs []string) ([]MetadataTokenImage, error) {
	rows, err := q.db.Query(ctx, listTokenImagesByAddrs, addrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataTokenImage{}
	for rows.Next() {
		var i MetadataTokenImage
		if err := rows.Scan(
			&i.ID,
			&i.TokenAddress,
			&i.ImageType,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenMetadataByAddrs = `-- name: ListTokenMetadataByAddrs :many
SELECT token_address, pool_address, name, symbol, description, website, twitter, telegram, discord, custom_tags, created_by, created_at, updated_at, decimals FROM metadata.token_metadata
WHERE LOWER(token_address) = ANY($1::text[])
`

func (q *Queries) ListTokenMetadataByAddrs(ctx context.Context, addrs []string) ([]MetadataTokenMetadatum, error) {
	rows, err := q.db.Query(ctx, listTokenMetadataByAddrs, addrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataTokenMetadatum{}
	for rows.Next() {
		var i MetadataTokenMetadatum
		if err := rows.Scan(
			&i.TokenAddress,
			&i.PoolAddress,
			&i.Name,
			&i.Symbol,
			&i.Description,
			&i.Website,
			&i.Twitter,
			&i.Telegram,
			&i.Discord,
			&i.CustomTags,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Decimals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTokenImage = `-- name: UpsertTokenImage :exec
INSERT INTO metadata.token_images (
	id, token_address, image_type, storage_key, mime_type, size_bytes, uploaded_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
	storage_key = EXCLUDED.storage_key,
	mime_type   = EXCLUDED.mime_type,
	size_bytes  = EXCLUDED.size_bytes,
	uploaded_at = EXCLUDED.uploaded_at
`

type UpsertTokenImageParams struct {
	ID           string
	TokenAddress string
	ImageType    string
	StorageKey   string
	MimeType     string
	SizeBytes    int32
	UploadedAt   int64
}

func (q *Queries) UpsertTokenImage(ctx context.Context, arg UpsertTokenImageParams) error {
	_, err := q.db.Exec(ctx, upsertTokenImage,
		arg.ID,
		arg.TokenAddress,
		arg.ImageType,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedAt,
	)
	return err
}

const upsertTokenMetadata = `-- name: UpsertTokenMetadata :exec
INSERT INTO metadata.token_metadata (
	token_address, pool_address, name, symbol, description,
	website, twitter, telegram, discord, custom_tags,
	decimals, created_by, created_at, updated_at
) VALUES (
	$1, $2, $3, $4, $5,
	$6, $7, $8, $9, $10,
	$11, $12, $13, $14
)
ON CONFLICT (token_address) DO UPDATE SET
	name        = EXCLUDED.name,
	symbol      = EXCLUDED.symbol,
	description = EXCLUDED.description,
	website     = EXCLUDED.website,
	twitter     = EXCLUDED.twitter,
	telegram    = EXCLUDED.telegram,
	discord     = EXCLUDED.discord,
	custom_tags = EXCLUDED.custom_tags,
	decimals    = EXCLUDED.decimals,
	updated_at  = EXCLUDED.updated_at
`

type UpsertTokenMetadataParams struct {
	TokenAddress string
	PoolAddress  string
	Name         pgtype.Text
	Symbol       pgtype.Text
	Description  pgtype.Text
	Website      pgtype.Text
	Twitter      pgtype.Text
	Telegram     pgtype.Text
	Discord      pgtype.Text
	CustomTags   pgtype.Text
	Decimals     int32
	CreatedBy    string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) UpsertTokenMetadata(ctx context.Context, arg UpsertTokenMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertTokenMetadata,
		arg.TokenAddress,
		arg.PoolAddress,
		arg.Name,
		arg.Symbol,
		arg.Description,
		arg.Website,
		arg.Twitter,
		arg.Telegram,
		arg.Discord,
		arg.CustomTags,
		arg.Decimals,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
