// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatChatBan struct {
	ID          string
	Wallet      string
	PoolAddress *string
	Reason      pgtype.Text
	BannedBy    string
	ExpiresAt   pgtype.Int8
	CreatedAt   int64
}

type ChatChatReport struct {
	ID         string
	MessageID  string
	ReportedBy string
	Reason     string
	Status     string
	CreatedAt  int64
}

type ChatComment struct {
	ID          string
	PoolAddress string
	Author      string
	Content     string
	ParentID    pgtype.Text
	Deleted     bool
	EditedAt    pgtype.Int8
	CreatedAt   int64
}

type ChatCommentLike struct {
	CommentID string
	Wallet    string
	CreatedAt int64
}

type ChatDmConversation struct {
	ID            string
	WalletA       string
	WalletB       string
	LastMessageAt pgtype.Int8
}

type ChatDmMessage struct {
	ID             string
	ConversationID string
	Sender         string
	Content        string
	CreatedAt      int64
}

type ChatFollow struct {
	Follower  string
	Followee  string
	CreatedAt int64
}

type ChatPoolMessage struct {
	ID          string
	PoolAddress string
	Sender      string
	Content     string
	ReplyToID   pgtype.Text
	Deleted     bool
	EditedAt    pgtype.Int8
	CreatedAt   int64
}

type IndexerPool struct {
	PoolAddress  string
	TokenAddress string
	Creator      string
	CreatedAt    int64
}
