// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	// Mirrors the TS checkBan: a NULL pool narg matches GLOBAL bans only; a set pool
	// narg matches global OR that pool (because pool_address = NULL is never true).
	ActiveBans(ctx context.Context, arg ActiveBansParams) ([]ActiveBansRow, error)
	CountFollowers(ctx context.Context, followee string) (int64, error)
	CountFollowing(ctx context.Context, follower string) (int64, error)
	DeleteBan(ctx context.Context, id string) error
	// ── Followers graph (sign-free) ──────────────────────────────────────────────
	Follow(ctx context.Context, arg FollowParams) error
	GetComment(ctx context.Context, id string) (GetCommentRow, error)
	GetDmConversation(ctx context.Context, id string) (ChatDmConversation, error)
	// ── Cross-schema: indexer.pools (creator lookup for delete authorization) ─────
	GetPoolCreator(ctx context.Context, poolAddress string) (string, error)
	GetPoolMessage(ctx context.Context, arg GetPoolMessageParams) (GetPoolMessageRow, error)
	// ── Moderation: bans & reports ───────────────────────────────────────────────
	InsertBan(ctx context.Context, arg InsertBanParams) error
	// ── Comments feed (threaded, sign-free) ──────────────────────────────────────
	InsertComment(ctx context.Context, arg InsertCommentParams) error
	InsertDmMessage(ctx context.Context, arg InsertDmMessageParams) error
	InsertPoolMessage(ctx context.Context, arg InsertPoolMessageParams) error
	InsertReport(ctx context.Context, arg InsertReportParams) error
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	LikeComment(ctx context.Context, arg LikeCommentParams) error
	ListBans(ctx context.Context) ([]ChatChatBan, error)
	ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error)
	ListDmConversations(ctx context.Context, walletA string) ([]ChatDmConversation, error)
	ListDmMessages(ctx context.Context, arg ListDmMessagesParams) ([]ChatDmMessage, error)
	ListFollowers(ctx context.Context, followee string) ([]ListFollowersRow, error)
	ListFollowing(ctx context.Context, follower string) ([]ListFollowingRow, error)
	// query.sql — sqlc query definitions for media/social. Ports the TS chat
	// drizzle calls (pool chat, DMs, moderation) and adds the net-new comments +
	// followers surfaces. All wallet/pool values are normalized to lowercase by the
	// handlers on the way in, so matches are EXACT (no LOWER()) to keep the btree
	// indexes sargable under the 500K-concurrency bar.
	// ── Pool chat messages ───────────────────────────────────────────────────────
	ListPoolMessages(ctx context.Context, arg ListPoolMessagesParams) ([]ListPoolMessagesRow, error)
	ListReportsByStatus(ctx context.Context, status string) ([]ChatChatReport, error)
	SoftDeleteComment(ctx context.Context, id string) error
	SoftDeletePoolMessage(ctx context.Context, id string) error
	Unfollow(ctx context.Context, arg UnfollowParams) error
	UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error
	UpdateCommentContent(ctx context.Context, arg UpdateCommentContentParams) error
	UpdatePoolMessageContent(ctx context.Context, arg UpdatePoolMessageContentParams) error
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error
	// ── Direct messages ──────────────────────────────────────────────────────────
	UpsertDmConversation(ctx context.Context, arg UpsertDmConversationParams) error
}

var _ Querier = (*Queries)(nil)
