// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBans = `-- name: ActiveBans :many
SELECT id, reason FROM chat.chat_bans
WHERE wallet = $1
  AND (expires_at IS NULL OR expires_at > $2)
  AND (pool_address IS NULL OR pool_address = $3)
`

type ActiveBansParams struct {
	Wallet      string
	Now         pgtype.Int8
	PoolAddress *string
}

type ActiveBansRow struct {
	ID     string
	Reason pgtype.Text
}

// Mirrors the TS checkBan: a NULL pool narg matches GLOBAL bans only; a set pool
// narg matches global OR that pool (because pool_address = NULL is never true).
func (q *Queries) ActiveBans(ctx context.Context, arg ActiveBansParams) ([]ActiveBansRow, error) {
	rows, err := q.db.Query(ctx, activeBans, arg.Wallet, arg.Now, arg.PoolAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveBansRow{}
	for rows.Next() {
		var i ActiveBansRow
		if err := rows.Scan(&i.ID, &i.Reason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFollowers = `-- name: CountFollowers :one
SELECT count(*) FROM chat.follows WHERE followee = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followee string) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followee)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT count(*) FROM chat.follows WHERE follower = $1
`

func (q *Queries) CountFollowing(ctx context.Context, follower string) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, follower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBan = `-- name: DeleteBan :exec
DELETE FROM chat.chat_bans WHERE id = $1
`

func (q *Queries) DeleteBan(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBan, id)
	return err
}

const follow = `-- name: Follow :exec

INSERT INTO chat.follows (follower, followee, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (follower, followee) DO NOTHING
`

type FollowParams struct {
	Follower  string
	Followee  string
	CreatedAt int64
}

// ── Followers graph (sign-free) ──────────────────────────────────────────────
func (q *Queries) Follow(ctx context.Context, arg FollowParams) error {
	_, err := q.db.Exec(ctx, follow, arg.Follower, arg.Followee, arg.CreatedAt)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, pool_address, author, deleted FROM chat.comments
WHERE id = $1
LIMIT 1
`

type GetCommentRow struct {
	ID          string
	PoolAddress string
	Author      string
	Deleted     bool
}

func (q *Queries) GetComment(ctx context.Context, id string) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.PoolAddress,
		&i.Author,
		&i.Deleted,
	)
	return i, err
}

const getDmConversation = `-- name: GetDmConversation :one
SELECT id, wallet_a, wallet_b, last_message_at FROM chat.dm_conversations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDmConversation(ctx context.Context, id string) (ChatDmConversation, error) {
	row := q.db.QueryRow(ctx, getDmConversation, id)
	var i ChatDmConversation
	err := row.Scan(
		&i.ID,
		&i.WalletA,
		&i.WalletB,
		&i.LastMessageAt,
	)
	return i, err
}

const getPoolCreator = `-- name: GetPoolCreator :one

SELECT creator FROM indexer.pools WHERE pool_address = $1 LIMIT 1
`

// ── Cross-schema: indexer.pools (creator lookup for delete authorization) ─────
func (q *Queries) GetPoolCreator(ctx context.Context, poolAddress string) (string, error) {
	row := q.db.QueryRow(ctx, getPoolCreator, poolAddress)
	var creator string
	err := row.Scan(&creator)
	return creator, err
}

const getPoolMessage = `-- name: GetPoolMessage :one
SELECT id, sender, deleted FROM chat.pool_messages
WHERE id = $1 AND pool_address = $2
LIMIT 1
`

type GetPoolMessageParams struct {
	ID          string
	PoolAddress string
}

type GetPoolMessageRow struct {
	ID      string
	Sender  string
	Deleted bool
}

func (q *Queries) GetPoolMessage(ctx context.Context, arg GetPoolMessageParams) (GetPoolMessageRow, error) {
	row := q.db.QueryRow(ctx, getPoolMessage, arg.ID, arg.PoolAddress)
	var i GetPoolMessageRow
	err := row.Scan(&i.ID, &i.Sender, &i.Deleted)
	return i, err
}

const insertBan = `-- name: InsertBan :exec

INSERT INTO chat.chat_bans (id, wallet, pool_address, reason, banned_by, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertBanParams struct {
	ID          string
	Wallet      string
	PoolAddress *string
	Reason      pgtype.Text
	BannedBy    string
	ExpiresAt   pgtype.Int8
	CreatedAt   int64
}

// ── Moderation: bans & reports ───────────────────────────────────────────────
func (q *Queries) InsertBan(ctx context.Context, arg InsertBanParams) error {
	_, err := q.db.Exec(ctx, insertBan,
		arg.ID,
		arg.Wallet,
		arg.PoolAddress,
		arg.Reason,
		arg.BannedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertComment = `-- name: InsertComment :exec

INSERT INTO chat.comments (id, pool_address, author, content, parent_id, deleted, created_at)
VALUES ($1, $2, $3, $4, $5, false, $6)
`

type InsertCommentParams struct {
	ID          string
	PoolAddress string
	Author      string
	Content     string
	ParentID    pgtype.Text
	CreatedAt   int64
}

// ── Comments feed (threaded, sign-free) ──────────────────────────────────────
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.PoolAddress,
		arg.Author,
		arg.Content,
		arg.ParentID,
		arg.CreatedAt,
	)
	return err
}

const insertDmMessage = `-- name: InsertDmMessage :exec
INSERT INTO chat.dm_messages (id, conversation_id, sender, content, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDmMessageParams struct {
	ID             string
	ConversationID string
	Sender         string
	Content        string
	CreatedAt      int64
}

func (q *Queries) InsertDmMessage(ctx context.Context, arg InsertDmMessageParams) error {
	_, err := q.db.Exec(ctx, insertDmMessage,
		arg.ID,
		arg.ConversationID,
		arg.Sender,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const insertPoolMessage = `-- name: InsertPoolMessage :exec
INSERT INTO chat.pool_messages (
	id, pool_address, sender, content, reply_to_id, deleted, created_at
) VALUES ($1, $2, $3, $4, $5, false, $6)
`

type InsertPoolMessageParams struct {
	ID          string
	PoolAddress string
	Sender      string
	Content     string
	ReplyToID   pgtype.Text
	CreatedAt   int64
}

func (q *Queries) InsertPoolMessage(ctx context.Context, arg InsertPoolMessageParams) error {
	_, err := q.db.Exec(ctx, insertPoolMessage,
		arg.ID,
		arg.PoolAddress,
		arg.Sender,
		arg.Content,
		arg.ReplyToID,
		arg.CreatedAt,
	)
	return err
}

const insertReport = `-- name: InsertReport :exec
INSERT INTO chat.chat_reports (id, message_id, reported_by, reason, status, created_at)
VALUES ($1, $2, $3, $4, 'pending', $5)
`

type InsertReportParams struct {
	ID         string
	MessageID  string
	ReportedBy string
	Reason     string
	CreatedAt  int64
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.Exec(ctx, insertReport,
		arg.ID,
		arg.MessageID,
		arg.ReportedBy,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
	SELECT 1 FROM chat.follows WHERE follower = $1 AND followee = $2
) AS following
`

type IsFollowingParams struct {
	Follower string
	Followee string
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.Follower, arg.Followee)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const likeComment = `-- name: LikeComment :exec
INSERT INTO chat.comment_likes (comment_id, wallet, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (comment_id, wallet) DO NOTHING
`

type LikeCommentParams struct {
	CommentID string
	Wallet    string
	CreatedAt int64
}

func (q *Queries) LikeComment(ctx context.Context, arg LikeCommentParams) error {
	_, err := q.db.Exec(ctx, likeComment, arg.CommentID, arg.Wallet, arg.CreatedAt)
	return err
}

const listBans = `-- name: ListBans :many
SELECT id, wallet, pool_address, reason, banned_by, expires_at, created_at
FROM chat.chat_bans
ORDER BY created_at DESC
`

func (q *Queries) ListBans(ctx context.Context) ([]ChatChatBan, error) {
	rows, err := q.db.Query(ctx, listBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatChatBan{}
	for rows.Next() {
		var i ChatChatBan
		if err := rows.Scan(
			&i.ID,
			&i.Wallet,
			&i.PoolAddress,
			&i.Reason,
			&i.BannedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT
	c.id, c.pool_address, c.author, c.content, c.parent_id, c.edited_at, c.created_at,
	(SELECT count(*) FROM chat.comment_likes l WHERE l.comment_id = c.id) AS like_count
FROM chat.comments c
WHERE c.pool_address = $1 AND c.deleted = false
  AND ($2::text IS NULL OR c.id < $2)
ORDER BY c.created_at DESC
LIMIT $3
`

type ListCommentsParams struct {
	PoolAddress string
	Before      pgtype.Text
	Lim         int32
}

type ListCommentsRow struct {
	ID          string
	PoolAddress string
	Author      string
	Content     string
	ParentID    pgtype.Text
	EditedAt    pgtype.Int8
	CreatedAt   int64
	LikeCount   int64
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, arg.PoolAddress, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolAddress,
			&i.Author,
			&i.Content,
			&i.ParentID,
			&i.EditedAt,
			&i.CreatedAt,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDmConversations = `-- name: ListDmConversations :many
SELECT id, wallet_a, wallet_b, last_message_at FROM chat.dm_conversations
WHERE wallet_a = $1 OR wallet_b = $1
ORDER BY last_message_at DESC NULLS LAST
`

func (q *Queries) ListDmConversations(ctx context.Context, walletA string) ([]ChatDmConversation, error) {
	rows, err := q.db.Query(ctx, listDmConversations, walletA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatDmConversation{}
	for rows.Next() {
		var i ChatDmConversation
		if err := rows.Scan(
			&i.ID,
			&i.WalletA,
			&i.WalletB,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDmMessages = `-- name: ListDmMessages :many
SELECT id, conversation_id, sender, content, created_at FROM chat.dm_messages
WHERE conversation_id = $1
  AND ($2::text IS NULL OR id < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListDmMessagesParams struct {
	ConversationID string
	Before         pgtype.Text
	Lim            int32
}

func (q *Queries) ListDmMessages(ctx context.Context, arg ListDmMessagesParams) ([]ChatDmMessage, error) {
	rows, err := q.db.Query(ctx, listDmMessages, arg.ConversationID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatDmMessage{}
	for rows.Next() {
		var i ChatDmMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT follower, created_at FROM chat.follows
WHERE followee = $1
ORDER BY created_at DESC
`

type ListFollowersRow struct {
	Follower  string
	CreatedAt int64
}

func (q *Queries) ListFollowers(ctx context.Context, followee string) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, followee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(&i.Follower, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT followee, created_at FROM chat.follows
WHERE follower = $1
ORDER BY created_at DESC
`

type ListFollowingRow struct {
	Followee  string
	CreatedAt int64
}

func (q *Queries) ListFollowing(ctx context.Context, follower string) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, follower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(&i.Followee, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolMessages = `-- name: ListPoolMessages :many


SELECT id, pool_address, sender, content, reply_to_id, edited_at, created_at
FROM chat.pool_messages
WHERE pool_address = $1 AND deleted = false
  AND ($2::text IS NULL OR id < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListPoolMessagesParams struct {
	PoolAddress string
	Before      pgtype.Text
	Lim         int32
}

type ListPoolMessagesRow struct {
	ID          string
	PoolAddress string
	Sender      string
	Content     string
	ReplyToID   pgtype.Text
	EditedAt    pgtype.Int8
	CreatedAt   int64
}

// query.sql — sqlc query definitions for media/social. Ports the TS chat
// drizzle calls (pool chat, DMs, moderation) and adds the net-new comments +
// followers surfaces. All wallet/pool values are normalized to lowercase by the
// handlers on the way in, so matches are EXACT (no LOWER()) to keep the btree
// indexes sargable under the 500K-concurrency bar.
// ── Pool chat messages ───────────────────────────────────────────────────────
func (q *Queries) ListPoolMessages(ctx context.Context, arg ListPoolMessagesParams) ([]ListPoolMessagesRow, error) {
	rows, err := q.db.Query(ctx, listPoolMessages, arg.PoolAddress, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoolMessagesRow{}
	for rows.Next() {
		var i ListPoolMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolAddress,
			&i.Sender,
			&i.Content,
			&i.ReplyToID,
			&i.EditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByStatus = `-- name: ListReportsByStatus :many
SELECT id, message_id, reported_by, reason, status, created_at
FROM chat.chat_reports
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsByStatus(ctx context.Context, status string) ([]ChatChatReport, error) {
	rows, err := q.db.Query(ctx, listReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatChatReport{}
	for rows.Next() {
		var i ChatChatReport
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ReportedBy,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE chat.comments SET deleted = true WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const softDeletePoolMessage = `-- name: SoftDeletePoolMessage :exec
UPDATE chat.pool_messages SET deleted = true WHERE id = $1
`

func (q *Queries) SoftDeletePoolMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeletePoolMessage, id)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM chat.follows WHERE follower = $1 AND followee = $2
`

type UnfollowParams struct {
	Follower string
	Followee string
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.Exec(ctx, unfollow, arg.Follower, arg.Followee)
	return err
}

const unlikeComment = `-- name: UnlikeComment :exec
DELETE FROM chat.comment_likes WHERE comment_id = $1 AND wallet = $2
`

type UnlikeCommentParams struct {
	CommentID string
	Wallet    string
}

func (q *Queries) UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeComment, arg.CommentID, arg.Wallet)
	return err
}

const updateCommentContent = `-- name: UpdateCommentContent :exec
UPDATE chat.comments SET content = $2, edited_at = $3 WHERE id = $1
`

type UpdateCommentContentParams struct {
	ID       string
	Content  string
	EditedAt pgtype.Int8
}

func (q *Queries) UpdateCommentContent(ctx context.Context, arg UpdateCommentContentParams) error {
	_, err := q.db.Exec(ctx, updateCommentContent, arg.ID, arg.Content, arg.EditedAt)
	return err
}

const updatePoolMessageContent = `-- name: UpdatePoolMessageContent :exec
UPDATE chat.pool_messages SET content = $2, edited_at = $3 WHERE id = $1
`

type UpdatePoolMessageContentParams struct {
	ID       string
	Content  string
	EditedAt pgtype.Int8
}

func (q *Queries) UpdatePoolMessageContent(ctx context.Context, arg UpdatePoolMessageContentParams) error {
	_, err := q.db.Exec(ctx, updatePoolMessageContent, arg.ID, arg.Content, arg.EditedAt)
	return err
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE chat.chat_reports SET status = $2 WHERE id = $1
`

type UpdateReportStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportStatus, arg.ID, arg.Status)
	return err
}

const upsertDmConversation = `-- name: UpsertDmConversation :exec

INSERT INTO chat.dm_conversations (id, wallet_a, wallet_b, last_message_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET last_message_at = EXCLUDED.last_message_at
`

type UpsertDmConversationParams struct {
	ID            string
	WalletA       string
	WalletB       string
	LastMessageAt pgtype.Int8
}

// ── Direct messages ──────────────────────────────────────────────────────────
func (q *Queries) UpsertDmConversation(ctx context.Context, arg UpsertDmConversationParams) error {
	_, err := q.db.Exec(ctx, upsertDmConversation,
		arg.ID,
		arg.WalletA,
		arg.WalletB,
		arg.LastMessageAt,
	)
	return err
}
